name: Build APK and IPA (Cordova) on PR Merge

on:
  push:
    branches:
      - main

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          disable-animations: true

      - name: Install Android Build Tools 30.0.3
        run: |
          yes | sdkmanager "build-tools;30.0.3" "platforms;android-30"

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic & Cordova CLI
        run: npm install -g @ionic/cli cordova

      - name: Build Android APK (Debug)
        run: |
          ionic cordova build android

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

  ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic & Cordova CLI
        run: |
          npm install -g @ionic/cli cordova

      - name: Build iOS App
        run: |
          ionic cordova build ios --release

      - name: Upload IPA (manual export needed)
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-folder
          path: platforms/ios/build/device/
