name: Build Ionic APK and IPA on Merge

on:
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic and Capacitor
        run: |
          npm install -g @ionic/cli
          npm install -g @capacitor/cli

      - name: Build Web Assets
        run: ionic build

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build APK using Gradle
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

  # Optional: iOS build on macOS
  build_ios:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic and Capacitor
        run: |
          npm install -g @ionic/cli
          npm install -g @capacitor/cli

      - name: Build Web Assets
        run: ionic build

      - name: Sync Capacitor
        run: npx cap sync ios

      - name: Build IPA with Xcode
        run: |
          cd ios/App
          xcodebuild -scheme App -configuration Release -archivePath build/App.xcarchive archive
          xcodebuild -exportArchive -archivePath build/App.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.ipa
          path: ios/App/build/*.ipa
