name: Build APK and IPA (Cordova) on PR Merge

on:
  push:
    branches:
      - main

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic & Cordova CLI
        run: |
          npm install -g @ionic/cli cordova

      - name: Build Android APK (Unsigned)
        run: |
          ionic cordova build android --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned.apk
          path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk

  ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic & Cordova CLI
        run: |
          npm install -g @ionic/cli cordova

      - name: Build iOS App
        run: |
          ionic cordova build ios --release

      # Exporting IPA requires a bit more setup with signing, e.g.:
      # - Setup code signing via fastlane or xcodebuild
      # - Export using xcodebuild or fastlane

      - name: Upload IPA (manual export needed)
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-folder
          path: platforms/ios/build/device/
